### ISSUE TITLE
HDF5 backend tests fail

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#100]
Having just gotten HDF5 working on OS X 10.7, the unit tests now fail:
# 

  FAIL: test_simple_sample (pymc.tests.test_database.testHDF5Objects)

---

  Traceback (most recent call last):
    File "/Users/fonnescj/Code/pymc/pymc/tests/test_database.py", line 332, in test_simple_sample
      assert_array_equal(self.S.trace('K')[:].shape, (10,))
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 753, in assert_array_equal
      verbose=verbose, header='Arrays are not equal')
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 677, in assert_array_compare
      raise AssertionError(msg)
  AssertionError: 
  Arrays are not equal

  (mismatch 100.0%)
   x: array([0])
   y: array([10])

  ======================================================================
  FAIL: test_xload (pymc.tests.test_database.testHDF5Objects)

---

  Traceback (most recent call last):
    File "/Users/fonnescj/Code/pymc/pymc/tests/test_database.py", line 345, in test_xload
      assert_array_equal(db.K().shape, (10,))
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 753, in assert_array_equal
      verbose=verbose, header='Arrays are not equal')
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 677, in assert_array_compare
      raise AssertionError(msg)
  AssertionError: 
  Arrays are not equal

  (mismatch 100.0%)
   x: array([0])
   y: array([10])

  ======================================================================
  FAIL: test_yconnect_and_sample (pymc.tests.test_database.testHDF5Objects)

---

  Traceback (most recent call last):
    File "/Users/fonnescj/Code/pymc/pymc/tests/test_database.py", line 356, in test_yconnect_and_sample
      assert_array_equal(db.K(chain=1).shape, (10,))
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 753, in assert_array_equal
      verbose=verbose, header='Arrays are not equal')
    File "/Library/Python/2.7/site-packages/numpy-1.7.0.dev_3503c5f_20120323-py2.7-macosx-10.7-x86_64.egg/numpy/testing/utils.py", line 677, in assert_array_compare
      raise AssertionError(msg)
  AssertionError: 
  Arrays are not equal

  (mismatch 100.0%)
   x: array([0])
   y: array([10])

**Comment by fonnesbeck** [comment]
Apparently, the HDF5 backend does not tally objects in subsequent chains after the initial one. Works fine for numeric chains, however.

**Comment by fonnesbeck** [comment]
When the HDF5 backend initializes, somehow it blows away the existing traces for object types.

**Comment by fonnesbeck** [comment]
Yes, when _initialize is called on hdf5.Database, all TraceObjects disappear. That is, its _vlarrays list is empty. 

```
(Pdb) self._traces['K']._vlarrays
[]
```

However, it is there when the first chain completes sampling.

```
In [9]: S.db.trace('K')._vlarrays
Out[9]: 
[/chain0/group0/K_0 (VLArray(10,)) 'K samples.'
  atom = ObjectAtom()
  byteorder = 'little'
  nrows = 10
  flavor = 'numpy']
```

Completely stumped.

**Comment by fonnesbeck** [comment]
Removed these tests from the test suite, as well as the zcompression test.
