### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by nhmc** [pymc-devs/pymc3#102]
Hi,

I just downloaded and installed the latest development version of pymc (latest commit cd07a7a94bb000579969a772827c07e26cb740cc), and there were a lot of test failures. The output of pymc.test() is below. I'm using ubuntu version 11.04 on a 64 bit system.

```
In [5]: pymc.test()
Running unit tests for pymc.tests
NumPy version 1.5.1
NumPy is installed in /usr/local/lib/python2.7/dist-packages/numpy
Python version 2.7.1+ (r271:86832, Apr 11 2011, 18:13:53) [GCC 4.5.2]
nose version 0.11.4
.............................E.............S......FFF.......F............................................................................F.......F..........................
======================================================================
ERROR: test_zcompression (pymc.tests.test_database.TestHDF5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_database.py", line 280, in test_zcompression
    S = MCMC(disaster_model, db=db)
  File "/usr/local/lib/python2.7/dist-packages/pymc/MCMC.py", line 71, in __init__
    Sampler.__init__(self, input, db, name, calc_deviance=calc_deviance, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pymc/Model.py", line 212, in __init__
    v.trace = self.db._traces[v.__name__]
KeyError: 'late_mean'

======================================================================
FAIL: test_simple_sample (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_database.py", line 323, in test_simple_sample
    assert_array_equal(self.S.trace('K', chain=None)[:].shape, (5,))
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 686, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 618, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([45])
 y: array([5])

======================================================================
FAIL: test_xload (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_database.py", line 344, in test_xload
    assert_array_equal(db.B().shape, (10,))
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 686, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 618, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([5])
 y: array([10])

======================================================================
FAIL: test_yconnect_and_sample (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_database.py", line 356, in test_yconnect_and_sample
    assert_array_equal(db.K(chain=1).shape, (10,))
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 686, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 618, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([0])
 y: array([10])

======================================================================
FAIL: test_random (pymc.tests.test_distributions.test_arlognormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_distributions.py", line 286, in test_random
    assert_almost_equal(corr, rho, 1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 463, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal
 ACTUAL: 0.73378260431604114
 DESIRED: 0.8

======================================================================
FAIL: test_random (pymc.tests.test_distributions.test_truncnorm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_distributions.py", line 936, in test_random
    assert_almost_equal(r.mean(), truncnorm_expval(-1, .1, -20., 20.), 1)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 463, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal
 ACTUAL: -0.94639768884730635
 DESIRED: -0.99999999820581786

======================================================================
FAIL: test_gradients (pymc.tests.test_gradients.test_gradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_gradients.py", line 305, in test_gradients
    check_gradients(chi2)
  File "/usr/local/lib/python2.7/dist-packages/pymc/tests/test_gradients.py", line 113, in check_gradients
    " is not correct.")
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 774, in assert_array_almost_equal
    header='Arrays are not almost equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 618, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal
analytic gradient for chi2 with respect to parameter chi2 is not correct.
(mismatch 20.0%)
 x: array([ -4.79623452e-01,  -3.19349880e-01,  -2.84632762e-01,
        -2.39573694e-01,  -1.04844309e+06])
 y: array([ -4.79624077e-01,  -3.19349001e-01,  -2.84635127e-01,
        -2.39572472e-01,  -1.04914927e+06])

----------------------------------------------------------------------
Ran 172 tests in 30.006s

FAILED (SKIP=1, errors=1, failures=6)
```

**Comment by fonnesbeck** [comment]
Most of these are related to your not having HDF5 installed correctly. The others should just be stochastic errors that should not occur regularly.

**Comment by nhmc** [comment]
Ok, great thanks.  Do you know how hdf5 is incorrectly installed?  My version is installed using the ubuntu package manager and it has been working ok with pytables so far.

**Comment by fonnesbeck** [comment]
Do the PyTables tests run clean? I work on OS X, so I don't have experience with HDF5 on Linux.

Looking at this again, your errors seem to be related to #100 where HDF5 fails for object storage. This won't cause any issue with PyMC with normal use, since we are not typically storing objects in the traces.

**Comment by nhmc** [comment]
The PyTables tests didn't run clean, so I reinstalled the latest version (2.3.1) and now all the PyTables tests pass. After I reinstalled pymc and re-ran the tests, I get similar failures to those described in #100. So I think you're right, it does look like the same problem described in that issue.

**Comment by fonnesbeck** [comment]
The remaining failures have to do with the storage of objects, which I believe will only be an issue with the GP module.
