### ISSUE TITLE
Make some of the tests (test_LazyFunction, test_gradients) more robust

### ISSUE THREAD

**Issue by yarikoptic** [pymc-devs/pymc3#134]
According to search this issue came up already before (at least for test_LazyFunction.py).  Some of the tests might fail from time to time.

```
** File "/home/yoh/deb/perspect/build-area/pymc-2.2+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_LazyFunction.py", line 96, in <module>
    assert_equal(L.get_cached_counts()[1,cur_frame], C.counter.get_count())
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 1
 DESIRED: 0

** File "/home/yoh/deb/perspect/build-area/pymc-2.2+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_gradients.py", line 325, in test_gradients
    check_gradients(chi2)
  File "/home/yoh/deb/perspect/build-area/pymc-2.2+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_gradients.py", line 132, in check_gradients
    " is not correct.")
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 800, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals
analytic gradient for chi2 with respect to parameter chi2 is not correct.
(mismatch 20.0%)
 x: array([ -2.53912447e-01,  -6.69935218e-02,  -3.84266602e+05,
        -2.51009880e-01,  -2.23842278e-01])
 y: array([ -2.53911573e-01,  -6.69956899e-02,  -3.84350653e+05,
        -2.51008824e-01,  -2.23843582e-01])
```

I am preparing a debian package (based on 2.2) for pymc and enabling unittesting at package build time.  Sure thing I could just skip those but IMHO it would be great if those tests could be made more robust either via pre-seeding of RNG or just lowering demanded precision.  Thanks in advance

**Comment by yarikoptic** [comment]
and more

```
======================================================================
FAIL: test_random (pymc.tests.test_distributions.test_arlognormal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/pymc/build/lib.linux-x86_64-2.7/pymc/tests/test_distributions.py", line 286, in test_random
    assert_almost_equal(corr, rho, 1)
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 468, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 1 decimals
 ACTUAL: 0.74988801253693471
 DESIRED: 0.8
```

may be you have a way to seed RNG from e.g. environment? (e.g. like we did in PyMVPA (MVPA_SEED), or in skilearn
https://github.com/scikit-learn/scikit-learn/blob/HEAD/sklearn/__init__.py#L73 )
to provide you with an easy way toward reproducing these cases?

**Comment by yarikoptic** [comment]
more

```
======================================================================
FAIL: test_consistency (pymc.tests.test_distributions.test_beta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/perspect/build-area/pymc-2.2+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_distributions.py", line 332, in test_consistency
    assert_array_almost_equal(hist, like,1)
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 800, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 1 decimals

(mismatch 10.0%)
 x: array([ 0.258,  1.256,  2.052,  2.104,  1.964,  1.35 ,  0.722,  0.252,
        0.038,  0.004])
 y: array([  2.37015648e-01,   1.19904062e+00,   2.03944501e+00,
         2.27232938e+00,   1.93510412e+00,   1.30081243e+00,
         6.69149143e-01,   2.36175448e-01,   4.27293655e-02,
         1.53209815e-03])
```

**Comment by yarikoptic** [comment]
```
======================================================================
FAIL: test_simple (pymc.tests.test_missing.TestMissing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/pymc-2.2+ds/build/lib.linux-x86_64-2.7/pymc/tests/test_missing.py", line 39, in test_simple
    assert_almost_equal(sum(sd2)/10000., 0.95, decimal=1)
  File "/usr/lib/pymodules/python2.7/numpy/testing/utils.py", line 468, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 1 decimals
 ACTUAL: 0.88939999999999997
 DESIRED: 0.95
```
