### ISSUE TITLE
Scipy Superpack on OS 10.7.5

### ISSUE THREAD

**Issue by chetan-guevara** [pymc-devs/pymc3#149]
I'm attempting to install the Scipy superpack on Mac OS 10.7.5. I installed the Scipy superpack and both numpy and scipy work fine. However I'm having problems importing the Pylab package. Below is the error I get. I've looked through online forums and none of the posted solutions seem to work. Any help would be very appreciated! 

---

> > > import pylab

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/pylab.py", line 268, in <module>
    from matplotlib.pyplot import *
  File "/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/pyplot.py", line 98, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/backends/backend_macosx.py", line 21, in <module>
    from matplotlib.backends import _macosx
ImportError: dlopen(/Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/backends/_macosx.so, 2): Library not loaded: /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
  Referenced from: /Library/Python/2.7/site-packages/matplotlib-1.3.x-py2.7-macosx-10.8-intel.egg/matplotlib/backends/_macosx.so
  Reason: image not found
## I had successfully installed Python, Scipy and Numpy. But I also needed Matplotlib. So installed that, and it seemed to be fine all expect for pylab … the one package I was needing! 

When I installed Scipy superpack, everything went fine except for the following issues: 

Failed to build or run libzmq detection test.

If you expected pyzmq to link against an installed libzmq, please check to make sure:

```
* You have a C compiler installed
* A development version of Python is installed (including headers)
* A development version of ZMQ >= 2.1.4 is installed (including headers)
* If ZMQ is not in a default location, supply the argument --zmq=<path>
* If you did recently install ZMQ to a default location,
  try rebuilding the ld cache with `sudo ldconfig`
  or specify zmq's location with `--zmq=/usr/local`
```

If you expected to get a binary install (egg), we have those for
current Pythons on OSX and Windows. These can be installed with
easy_install, but PIP DOES NOT SUPPORT EGGS.

You can skip all this detection/waiting nonsense if you know
you want pyzmq to bundle libzmq as an extension by passing:

```
`--zmq=bundled`
```

I will now try to build libzmq as a Python extension
unless you interrupt me (^C) in the next 10 seconds…

 1…

and then as it was creating this extension, I got another error: 

Adding pyzmq 2.2.0.1 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/pyzmq-2.2.0.1-py2.7-macosx-10.7-intel.egg
Error in at exit._run_exitfuncs
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 258, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.py", line 258, in _exit_function
    info('process shutting down')
TypeError: 'NoneType' object is not callable

**Comment by fonnesbeck** [comment]
The current superpack is not compatible with OS X 10.7.5. At the bottom of the home page, check out the "older releases" section on installing a suitable version.

**Comment by chetan-guevara** [comment]
Hi Chris,
I should have clarified in my original post. I installed the version for 10.7.4 (I didn't see one for 10.7.5). I don't know why matplotlib is declaring that it's using the egg for OS 10.8. Maybe that's the problem. Any thoughts?

**Comment by fonnesbeck** [comment]
Sounds like you may have answered "no" to the question about installing from a local repository. You should answer "yes", otherwise the script will go out and get the latest version of everything, rather than the eggs that are in the archive.

**Comment by frgomes** [comment]
Hello,

I'm not on a Mac, but eventually an article I've written can help you on 
this:
http://rgomes-info.blogspot.co.uk/2013/01/python-stack-for-gpu-programming.html

Cheers

Richard Gomes
http://rgomes.info

**Comment by chetan-guevara** [comment]
Thank you! Now it works!
