### ISSUE TITLE
Examples throw assert igrad is not None

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#166]
This is with most recent pymc3 and theano master.

``` python
>>python hierarchial.py 
Traceback (most recent call last):
  File "hierarchial.py", line 60, in <module>
    map_x = find_MAP(model, start)
  File "/home/whyking/tools/pymc_trunk/pymc/pymc/MAP.py", line 36, in find_MAP
    dlogp = model_dlogp(model, vars)
  File "/home/whyking/tools/pymc_trunk/pymc/pymc/core.py", line 111, in model_dlogp
    return model_func(model, dlogp_calc(model, dvars), mode)
  File "/home/whyking/tools/pymc_trunk/pymc/pymc/core.py", line 195, in der_calc
    return d_calc(logp_calc(model), dvars)
  File "/home/whyking/tools/pymc_trunk/pymc/pymc/core.py", line 124, in gradient
    return concatenate([flatgrad(f, v) for v in dvars])
  File "/home/whyking/tools/pymc_trunk/pymc/pymc/core.py", line 121, in flatgrad
    return flatten(grad(f, v))
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 525, in grad
    grad_dict, wrt, cost_name)
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 1056, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 1016, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 773, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 1016, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gradient.py", line 886, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 662, in grad
    rval = self._bgrad(inputs, ograds)
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 740, in _bgrad
    assert igrad is not None
AssertionError
```

**Comment by jsalvatier** [comment]
I think this is due to https://github.com/Theano/Theano/pull/1083 not being integrated yet. The hierarchical example uses advanced indexing, and needs a gradient, and this will fail without https://github.com/Theano/Theano/pull/1083. Hopefully that will be fixed soon. If you need this to work in the mean time, you can use my Theano branch https://github.com/jsalvatier/Theano-1/tree/advinc .

**Comment by twiecki** [comment]
Yes, that does the trick. Thanks!
