### ISSUE TITLE
Failing unittest for examples/hierarchical.py

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#196]
# 
## ERROR: tests.test_examples.test_examples('/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/../examples/hierarchical.py',)

Traceback (most recent call last):
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(_self.arg)
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/tests/test_examples.py", line 28, in check_example
    exec(c)
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/../examples/hierarchical.py", line 61, in <module>
    hess = approx_hess(model, map_x) #find a good orientation using the hessian at the MAP
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/num_derivatives.py", line 38, in approx_hess
    return nd.Jacobian(grad_logp)(bij.map(start))
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/numdifftools/core.py", line 862, in **call**
    return self.jacobian(x00)
  File "/home/whyking/envs/pymc3/local/lib/python2.7/site-packages/numdifftools/core.py", line 942, in jacobian
    fdif = fun(xp) - fun(xm)
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/num_derivatives.py", line 31, in grad_logp
    return np.nan_to_num(-dlogp(point))
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/core.py", line 295, in **call**
    return self.fn(self.bij.rmap(d))
  File "/home/whyking/tools/pymc_trunk/pymc_twiecki/pymc/core.py", line 106, in **call**
    return self.f(_*state)
  File "/home/whyking/tools/Theano-1/theano/compile/function_module.py", line 580, in **call**
    gof.vm.raise_with_op(self.fn.nodes[self.fn.position_of_error])
  File "/home/whyking/tools/Theano-1/theano/compile/function_module.py", line 574, in **call**
    outputs = self.fn()
  File "/home/whyking/tools/Theano-1/theano/gof/op.py", line 605, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/whyking/tools/Theano-1/theano/tensor/basic.py", line 6413, in perform
    increment(x,idx, y)
  File "/home/whyking/tools/Theano-1/theano/tensor/basic.py", line 6425, in inplace_increment1d_slow
    x[i] += y[j]
FloatingPointError: invalid value encountered in add

---

Ran 21 tests in 1247.890s

I believe this worked before. This is theano master branch.

**Comment by jsalvatier** [comment]
It seems that the numpy error settings have gotten changed somehow: http://docs.scipy.org/doc/numpy/reference/generated/numpy.seterr.html . This is surprising because I don't think 'raise' is the default.

**Comment by twiecki** [comment]
Oh weird, we had this before (discussed in a private email thread but no solution I can see).

Anway, not only does this happen for me locally but on travisCI as well.

**Comment by jsalvatier** [comment]
Hmm, yes I remember this now. It must be that we never fixed it. One way to 'fix' the issue is to get a numpy dev branch.

**Comment by twiecki** [comment]
Yeah, that fixes it. Maybe should add those points to the dependency information.
