### ISSUE TITLE
Dirichlet test fails on travis only

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#317]
```
ERROR: pymc.tests.test_examples.test_examples('/home/travis/build/pymc-devs/pymc/pymc/examples/dirichlet.py',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_examples.py", line 37, in check_example
    imp.load_source('__main__', path.basename(p))
  File "dirichlet.py", line 17, in <module>
    H = model.d2logpc()
  File "/home/travis/build/pymc-devs/pymc/pymc/model.py", line 84, in d2logpc
    return compilef(hessian(model.logp, vars))
  File "/home/travis/build/pymc-devs/pymc/pymc/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 89, in hessian
    return -jacobian(gradient(f, vars), vars)
  File "/home/travis/build/pymc-devs/pymc/pymc/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 84, in jacobian
    return t.concatenate([jacobian1(f, v) for v in vars], axis=1)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 76, in jacobian1
    return theano.map(grad_i, idx)[0]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/scan_module/scan_views.py", line 68, in map
    name=name)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/scan_module/scan.py", line 732, in scan
    condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 74, in grad_i
    return gradient1(f[i], v)
  File "/home/travis/build/pymc-devs/pymc/pymc/theanof.py", line 57, in gradient1
    return t.flatten(t.grad(f, v, disconnected_inputs='warn'))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 528, in grad
    grad_dict, wrt, cost_name)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1101, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 785, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 1061, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gradient.py", line 913, in access_term_cache
    node.outputs, new_output_grads):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/op.py", line 725, in get_debug_values
    rval.append(get_test_value(arg))
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/op.py", line 641, in get_test_value
    v_tensor = theano.tensor.as_tensor_variable(v)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/tensor/basic.py", line 217, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
AsTensorError: ('Cannot convert [Split{2}.0, Split{2}.1] to TensorType', <type 'list'>)
```

**Comment by twiecki** [comment]
Not sure why, but this doesn't seem to occur anymore.
