### ISSUE TITLE
ARM example fails with NumPy master

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc3#327]
```
======================================================================
ERROR: pymc.tests.test_examples.test_examples('/home/travis/build/pymc-devs/pymc/pymc/examples/ARM5-4.py',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pymc-devs/pymc/pymc/tests/test_examples.py", line 37, in check_example
    imp.load_source('__main__', path.basename(p))
  File "ARM5-4.py", line 36, in <module>
    start = find_MAP()
  File "/home/travis/build/pymc-devs/pymc/pymc/tuning/starting.py", line 46, in find_MAP
    dlogp = bij.mapf(model.dlogpc(vars))
  File "/home/travis/build/pymc-devs/pymc/pymc/model.py", line 81, in dlogpc
    return compilef(gradient(model.logp, vars))
  File "/home/travis/build/pymc-devs/pymc/pymc/memoize.py", line 14, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "/home/travis/build/pymc-devs/pymc/pymc/model.py", line 179, in compilef
    mode=mode)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/compile/function.py", line 223, in function
    profile=profile)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 512, in pfunc
    on_unused_input=on_unused_input)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1314, in orig_function
    defaults)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1183, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/link.py", line 434, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/vm.py", line 845, in make_all
    for node in order]
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/op.py", line 591, in make_thunk
    output_storage=node_output_storage)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 933, in make_thunk
    keep_lock=keep_lock)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 876, in __compile__
    keep_lock=keep_lock)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1297, in cthunk_factory
    key = self.cmodule_key()
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1017, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1145, in cmodule_key_
    for ipos, i in enumerate(node.inputs)),
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1145, in <genexpr>
    for ipos, i in enumerate(node.inputs)),
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1099, in in_sig
    isig = (isig[0].theano_hash(), topological_pos, i_idx)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/tensor/var.py", line 598, in theano_hash
    return hash_from_ndarray(d)
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/tensor/utils.py", line 25, in hash_from_ndarray
    hash_from_code(str(data.strides)) +
  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/theano/gof/cc.py", line 32, in hash_from_code
    return hashlib.md5(msg).hexdigest()
ValueError: ndarray is not C-contiguous
```

**Comment by fonnesbeck** [comment]
`test_examples` runs cleanly on my machine. Is this just a Theano version issue on Travis?

**Comment by twiecki** [comment]
Hrm, I also can't reproduce this locally. Travis installs the latest github version every time so it can't be that.

**Comment by twiecki** [comment]
Actually I can reproduce it locally now. Updating numpy and theano to master produces the behavior. So could be a numpy bug?

**Comment by twiecki** [comment]
So for some reason the matrix of dlogpc() is not C-aligned:

```
ValueError: ndarray is not C-contiguous
> /home/whyking/envs/pymc3/local/lib/python2.7/site-packages/theano/gof/cc.py(32)hash_from_code()
     31     def hash_from_code(msg):
---> 32         return hashlib.md5(msg).hexdigest()
     33 else:

ipdb> print msg.flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
ipdb> print msg.strides
(8, 40)
ipdb> print msg
[[ 0.70306954 -0.94693046  0.41306954 ..., -1.14693046 -1.01693046
  -0.99693046]
 [-0.31505862 -0.01009864 -0.27364864 ..., -0.40623862 -0.25489864
  -0.27487863]
 [-0.42284768 -0.42284768 -0.42284768 ..., -0.42284768 -0.42284768
   0.57715232]
 [-0.98940397 -0.98940397  1.01059603 ...,  0.01059603 -0.98940397
   0.01059603]
 [ 1.          1.          1.         ...,  1.          1.          1.        ]]
ipdb> print msg.shape
(5, 3020)
```

I tried adding `order='C'` to all data arrays in `ARM5-4.py` but the error persists.

So it seems there are a couple of open questions:
- Why does this only occur with `ARM5-4.py`?
- Why does this only occur with the most recent numpy? Is this a bug or just an additional test that was included? In the latter case it would seem that this is either a Theano or PyMC3 bug.

@jsalvatier any ideas? You know the guts of those 3 things best.

**Comment by jsalvatier** [comment]
I don't know what's going on. Since the error seems to arise in Theano, why
don't you make a Theano issue, and maybe they can give us an idea about
what to explore further. Then we can see if we can narrow down the problem.

**Comment by fonnesbeck** [comment]
Actually, I've seen this on Travis for the GLM example as well.

**Comment by lamblin** [comment]
(Coming from Theano's [thread](https://github.com/pymc-devs/pymc/issues/327) discussing this issue.)
My guess is that the behaviour of `hashlib.md5` on a non-contiguous array has changed in the latest version, and that hashing non-contiguous arrays is no longer allowed.
I cannot easily install the latest NumPy, but could you please try running the following?

``` Python
import numpy as np
from hashlib import md5
z = np.zeros((2, 3))
print md5(z).hexdigest()
print md5(z.T).hexdigest()
```

With NumPy 1.7.1, it prints `b203621a65475445e6fcdca717c667b5` twice.

**Comment by twiecki** [comment]
@lamblin Running this with most recent numpy produces the bug:

``` python
In [1]: import numpy as np

In [2]: from hashlib import md5

In [3]: z = np.zeros((2, 3))

In [4]: print md5(z).hexdigest()
b203621a65475445e6fcdca717c667b5

In [5]: print md5(z.T).hexdigest()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-0aa4d718ead7> in <module>()
----> 1 print md5(z.T).hexdigest()

ValueError: ndarray is not C-contiguous
```

**Comment by lamblin** [comment]
Thanks for the testing, it confirms something changed in NumPy.
I'll submit a fix to Theano so that we always convert arrays to C-contiguous ones before hashing them (for now, we tolerate F-contiguous as well, as it used to work).

**Comment by twiecki** [comment]
Sounds great, thanks for moving so quickly on this!

**Comment by twiecki** [comment]
@lamblin Thanks for fixing this!
