### ISSUE TITLE
PYMC 3 - Wishart distribution problem

### ISSUE THREAD

**Issue by jangevaare** [pymc-devs/pymc3#337]
New PYMC user here... I get an error when I try to specify a Wishart prior distribution... Not sure if this is a bug or if it's me. Any ideas?

e.g.

```
with Model() as model:
...     wishart_test=Wishart('wishart_test', n=3, p=2, V=np.eye(2))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/distributions/distribution.py", line 23, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/distributions/distribution.py", line 29, in dist
dist.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/quickclass.py", line 10, in __init__
    self.__dict__.update(f(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/quickclass.py", line 76, in newf
    r1 = f(*args_a, **kwargs_a)
  File "/usr/local/lib/python2.7/dist-packages/pymc-3.0-py2.7.egg/pymc/distributions/multivariate.py", line 164, in Wishart
nan)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0rc3-py2.7.egg/theano/gof/op.py", line 399, in __call__
node = self.make_node(*inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0rc3-py2.7.egg/theano/tensor/elemwise.py", line 532, in make_node
inputs = map(as_tensor_variable, inputs)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.6.0rc3-py2.7.egg/theano/tensor/basic.py", line 182, in as_tensor_variable
"Cannot cast True or False as a tensor variable. Please use 1 or "
theano.tensor.var.AsTensorError: Cannot cast True or False as a tensor variable. Please use 1 or 0. This error might be caused by using the == operator on Variables. v == w does not do what you think it does, use theano.tensor.eq(v, w) instead.
```

**Comment by jsalvatier** [comment]
This is definitely a bug on our end. Thanks for reporting it.

**Comment by jsalvatier** [comment]
Looks like the culprit is

```
mode = switch(n >= p + 1,
             (n - p - 1) * V,
              nan)
```

which should be

  mode = switch(1*(n >= p + 1),
                 (n - p - 1) \* V,
                  nan)

**Comment by jangevaare** [comment]
Thank you for taking a look at this.
