### ISSUE TITLE
TypeError when running example

### ISSUE THREAD

**Issue by brownto** [pymc-devs/pymc3#437]
I am trying to run the example at http://pymc-devs.github.io/pymc/README.html and get the following error. It appears that somewhere it is trying to do slicing with non-integers. I am running version 2.3 of pymc and downloaded the pymc library from http://www.lfd.uci.edu/~gohlke/pythonlibs/.

Traceback (most recent call last):
  File "C:\Python33\callPymodel.py", line 5, in <module>
    S.sample(iter=10000, burn=5000, thin=2)
  File "C:\Python33\lib\site-packages\pymc\MCMC.py", line 276, in sample
    Sampler.sample(self, iter, length, verbose)
  File "C:\Python33\lib\site-packages\pymc\Model.py", line 249, in sample
    self._loop()
  File "C:\Python33\lib\site-packages\pymc\MCMC.py", line 328, in _loop
    self.pbar.update(i)
  File "C:\Python33\lib\site-packages\pymc\progressbar.py", line 34, in update
    self.animate(i + 1, elapsed)
  File "C:\Python33\lib\site-packages\pymc\progressbar.py", line 51, in animate
    self.printer(self.progbar(i, elapsed))
  File "C:\Python33\lib\site-packages\pymc\progressbar.py", line 54, in progbar
    bar = self.bar(self.percentage(i))
  File "C:\Python33\lib\site-packages\pymc\progressbar.py", line 65, in bar
    return replace_at(bar, info, loc, loc + len(info))
  File "C:\Python33\lib\site-packages\pymc\progressbar.py", line 69, in replace_at
    return str[:start] + new + str[stop:]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by fonnesbeck** [comment]
That's an integer division bug that has been fixed since the release of PyMC 2.3. Can you try building from the current 2.3 branch?

**Comment by brownto** [comment]
I tried to install from the pymc 2.3 at https://pypi.python.org/pypi/pymc but it is for version 2.7 of Python and not version 3.3. It gives me an error since it can't find a reference to version 2.7 in the registry.
