### ISSUE TITLE
Testing framework hangs for Categorical distribution

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#438]
When running the test specified in `tests/test_cat.py` in the `categorical` branch, the test hangs for any valid parameters passed. I have isolated it to the `build_model` function in `test_distributions` but have not been able to get further. The likelihood is pretty simple, so I would not expect this to happen.

```
def categorical_logpdf(value, p):
    if value >= 0 and value <= len(p):
        return log(p[value]).sum()
    else:
        return -inf

def test_categorical():
    for n in [8, 12, 20]:
        yield check_categorical, n

def check_categorical(n):
    pymc_matches_scipy(
        Categorical, Domain(range(2, n, 2), 'int64'), {'p': Simplex(n)},
        lambda value, p: categorical_logpdf(value, p)
        )
```

**Comment by fonnesbeck** [comment]
OK, looks like `Simplex` is only intended for very small models (simplexes no larger than 3 or 4).

**Comment by jsalvatier** [comment]
Yes. That could be fixed by changing the sample points it returns to not be
exponentially large.

**Comment by fonnesbeck** [comment]
There does appear to be a problem with `check_logp` in `test_distributions`, however, that does not currently get caught because all of our distribution tests pass. When `assert_array_almost_equal` does not return `True` you get an error in `round`:

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/fonnescj/Code/pymc/pymc/tests/test_cat.py", line 32, in check_categorical
    lambda value, p: categorical_logpdf(value, p)
  File "/Users/fonnescj/Code/pymc/pymc/tests/test_distributions.py", line 325, in pymc_matches_scipy
    check_logp(model, value, domain, paramdomains, logp)
  File "/Users/fonnescj/Code/pymc/pymc/tests/test_distributions.py", line 430, in check_logp
    decimal=6, err_msg=str(pt))
  File "/Library/Python/2.7/site-packages/numpy-1.9.0.dev_78e29a3-py2.7-macosx-10.9-intel.egg/numpy/testing/utils.py", line 461, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Library/Python/2.7/site-packages/numpy-1.9.0.dev_78e29a3-py2.7-macosx-10.9-intel.egg/numpy/testing/utils.py", line 818, in assert_array_almost_equal
    header=('Arrays are not almost equal to %d decimals' % decimal))
  File "/Library/Python/2.7/site-packages/numpy-1.9.0.dev_78e29a3-py2.7-macosx-10.9-intel.egg/numpy/testing/utils.py", line 634, in assert_array_compare
    val = comparison(x, y)
  File "/Library/Python/2.7/site-packages/numpy-1.9.0.dev_78e29a3-py2.7-macosx-10.9-intel.egg/numpy/testing/utils.py", line 816, in compare
    return around(z, decimal) <= 10.0**(-decimal)
  File "/Library/Python/2.7/site-packages/numpy-1.9.0.dev_78e29a3-py2.7-macosx-10.9-intel.egg/numpy/core/fromnumeric.py", line 2610, in around
    return round(decimals, out)
TypeError: round() takes at most 2 arguments (3 given)
```

This seems to be related to `logp_reference(pt)`, where `pt` is a Point and `logp_reference` is the scipy distribution. It results in an unevaluated `Sum.0` rather than the value itself, which `assert_array_almost_equal` requires.

**Comment by fonnesbeck** [comment]
Figured it out.
