### ISSUE TITLE
IndexErrors in forestplot and traceplot

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#488]
Neither `traceplot` nor `forestplot` works anymore in master.

```
======================================================================
ERROR: pymc.tests.test_plots.test_plots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/fonnescj/Code/pymc/pymc/tests/test_plots.py", line 20, in test_plots
    forestplot(trace)
  File "/Users/fonnescj/Code/pymc/pymc/plots.py", line 329, in forestplot
    trace_quantiles = quantiles(tr, qlist)
  File "/Users/fonnescj/Code/pymc/pymc/stats.py", line 41, in wrapped_f
    return {v: f(pymc_obj[v][burn:], *args, **kwargs) for v in vars}
  File "/Users/fonnescj/Code/pymc/pymc/stats.py", line 41, in <dictcomp>
    return {v: f(pymc_obj[v][burn:], *args, **kwargs) for v in vars}
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 45, in __getitem__
    return self.point(index_value)
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 57, in point
    return dict((k, v.value[index]) for (k, v) in self.samples.items())
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 57, in <genexpr>
    return dict((k, v.value[index]) for (k, v) in self.samples.items())
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
-------------------- >> begin captured stdout << ---------------------
[-----------------97%----------------- ] 2930 of 3000 complete in 0.5 sec
[-----------------100%-----------------] 3000 of 3000 complete in 0.5 sec

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: pymc.tests.test_plots.test_multichain_plots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose-1.2.1-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/fonnescj/Code/pymc/pymc/tests/test_plots.py", line 36, in test_multichain_plots
    forestplot(ptrace, vars=['early_mean', 'late_mean'])
  File "/Users/fonnescj/Code/pymc/pymc/plots.py", line 290, in forestplot
    R = gelman_rubin(trace_obj)
  File "/Users/fonnescj/Code/pymc/pymc/diagnostics.py", line 163, in gelman_rubin
    x = np.array([mtrace.traces[i][var] for i in range(m)])
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 45, in __getitem__
    return self.point(index_value)
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 57, in point
    return dict((k, v.value[index]) for (k, v) in self.samples.items())
  File "/Users/fonnescj/Code/pymc/pymc/trace.py", line 57, in <genexpr>
    return dict((k, v.value[index]) for (k, v) in self.samples.items())
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

----------------------------------------------------------------------
Ran 2 tests in 44.915s

FAILED (errors=2)
```

**Comment by kyleam** [comment]
This is passing for me with pymc 7d6bd3d and numpy 3aa76ba.

**Comment by fonnesbeck** [comment]
Yep, this appears to be an incompatibility with the current Numpy master. Will open an issue there.

**Comment by QCaudron** [comment]
I'm getting the same error with PyMC 3.0 and numpy 1.9.0.

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-05774f276923> in <module>()
----> 1 pymc.traceplot(trace);

/Users/qcaudron/anaconda/lib/python2.7/site-packages/pymc/plots.pyc in traceplot(trace, vars, figsize, lines, combined, grid)
     60     for trace in traces:
     61         for i, v in enumerate(vars):
---> 62             d = np.squeeze(trace[v])
     63 
     64             if trace[v].dtype.kind == 'i':

/Users/qcaudron/anaconda/lib/python2.7/site-packages/pymc/trace.pyc in __getitem__(self, index_value)
     45         else:
     46             try:
---> 47                 return self.point(index_value)
     48             except ValueError:
     49                 pass

/Users/qcaudron/anaconda/lib/python2.7/site-packages/pymc/trace.pyc in point(self, index)
     57 
     58     def point(self, index):
---> 59         return dict((k, v.value[index]) for (k, v) in self.samples.items())
     60 
     61 

/Users/qcaudron/anaconda/lib/python2.7/site-packages/pymc/trace.pyc in <genexpr>((k, v))
     57 
     58     def point(self, index):
---> 59         return dict((k, v.value[index]) for (k, v) in self.samples.items())
     60 
     61 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by kyleam** [comment]
@QCaudron Is your pymc up-to-date? The current master branch doesn't contain a trace.py file.

**Comment by QCaudron** [comment]
I had just reinstalled using `pip install git+https://github.com/pymc-devs/pymc`. With your comment, I cloned the repo and installed from that instead, and now it's working. Thanks very much.

Also feels a load faster - is it just me ?
