### ISSUE TITLE
Exception: ("Compilation failed (return status=1) when fitting model

### ISSUE THREAD

**Issue by Hemming01** [pymc-devs/pymc3#5054]
Hello,

I'm trying to get pymc3 up and running. To test that I wanted to run the simple example below. I've followed the latest installation guide and tried uninstalling etc. several times. All packages seem to load correctly. Calling theano runs with no errors. I've been battling with this all day, trying all the solutions posted here and on other sites. I simply can't figure out what I'm doing wrong here.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pymc3 as pm

from pymc3 import *

size = 200
true_intercept = 1
true_slope = 2

x = np.linspace(0, 1, size)
# y = a + b*x
true_regression_line = true_intercept + true_slope * x
# add noise
y = true_regression_line + np.random.normal(scale=0.5, size=size)

data = dict(x=x, y=y)

fig = plt.figure(figsize=(7, 7))
ax = fig.add_subplot(111, xlabel="x", ylabel="y", title="Generated data and underlying model")
ax.plot(x, y, "x", label="sampled data")
ax.plot(x, true_regression_line, label="true regression line", lw=2.0)
plt.legend(loc=0);


with Model() as model:  # model specifications in PyMC3 are wrapped in a with-statement
    # Define priors
    sigma = HalfCauchy("sigma", beta=10, testval=1.0)
    intercept = Normal("Intercept", 0, sigma=20)
    x_coeff = Normal("x", 0, sigma=20)

    # Define likelihood
    likelihood = Normal("y", mu=intercept + x_coeff * x, sigma=sigma, observed=y)

    # Inference!
    trace = sample(3000, cores=2)  # draw 3000 posterior samples using NUTS sampling
```

**Please provide the full traceback.**

<details><summary>Complete error traceback</summary>

```python
Traceback (most recent call last):
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\Test.py", line 31, in <module>
    sigma = HalfCauchy("sigma", beta=10, testval=1.0)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\distributions\distribution.py", line 122, in __new__
    return model.Var(name, dist, data, total_size, dims=dims)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\model.py", line 1142, in Var
    var = TransformedRV(
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\model.py", line 2013, in __init__
    transformed_name, transform.apply(distribution), total_size=total_size
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\distributions\transforms.py", line 126, in apply
    return TransformedDistribution.dist(dist, self)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\distributions\distribution.py", line 130, in dist
    dist.__init__(*args, **kwargs)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\distributions\transforms.py", line 150, in __init__
    testval = forward(dist.default())
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\pymc3\distributions\transforms.py", line 218, in forward
    return tt.log(x)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\graph\op.py", line 253, in __call__
    compute_test_value(node)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\graph\op.py", line 126, in compute_test_value
    thunk = node.op.make_thunk(node, storage_map, compute_map, no_recycling=[])
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\graph\op.py", line 634, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\graph\op.py", line 600, in make_c_thunk
    outputs = cl.make_thunk(
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\basic.py", line 1203, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\basic.py", line 1138, in __compile__
    thunk, module = self.cthunk_factory(
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\basic.py", line 1634, in cthunk_factory
    module = get_module_cache().module_from_key(key=key, lnk=self)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\cmodule.py", line 1191, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\basic.py", line 1543, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\hemmi\PycharmProjects\pythonProject3\venv\lib\site-packages\theano\link\c\cmodule.py", line 2546, in compile_str
    raise Exception(
Exception: ("Compilation failed (return status=1): In file included from C:\\Users\\hemmi\\PycharmProjects\\pythonProject3\\venv\\lib\\site-packages\\numpy\\core\\include/numpy/ndarraytypes.h:4,.                  from C:\\Users\\hemmi\\PycharmProjects\\pythonProject3\\venv\\lib\\site-packages\\numpy\\core\\include/numpy/ndarrayobject.h:12,.                  from C:\\Users\\hemmi\\PycharmProjects\\pythonProject3\\venv\\lib\\site-packages\\numpy\\core\\include/numpy/arrayobject.h:4,.                  from C:\\Users\\hemmi\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\Local\\Theano\\compiledir_Windows-10-10.0.19043-SP0-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-3.9.7-64\\tmpcb46fgyg\\mod.cpp:5:. C:\\Users\\hemmi\\PycharmProjects\\pythonProject3\\venv\\lib\\site-packages\\numpy\\core\\include/numpy/npy_common.h:185:20: warning: 'int _fseeki64(FILE*, long long int, int)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes].   185 | extern int __cdecl _fseeki64(FILE *, long long, int);.       |                    ^~~~~~~~~. C:\\Users\\hemmi\\PycharmProjects\\pythonProject3\\venv\\lib\\site-packages\\numpy\\core\\include/numpy/npy_common.h:186:26: warning: 'long long int _ftelli64(FILE*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes].   186 | extern long long __cdecl _ftelli64(FILE *);.       |                          ^~~~~~~~~. cc1plus.exe: warning: unrecognized command line option '-Wno-c++11-narrowing'. C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file C:\\Users\\hemmi\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\Local\\Theano\\compiledir_Windows-10-10.0.19043-SP0-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-3.9.7-64\\tmpcb46fgyg\\mcec594bd93a9f0bf822b906a6f3c0143220942cc5f8b7ad4b91874d2a3b48485.pyd: No such file or directory\r. collect2.exe: error: ld returned 1 exit status. ", 'FunctionGraph(Elemwise{log,no_inplace}(TensorConstant{1.0}))')

```

</details>

**Please provide any additional information below.**

This is my environment variables for user in path.
![user path](https://user-images.githubusercontent.com/34618643/136459073-7f4c8eca-6208-46a5-8719-24390955ba20.png)

## Versions and main components

* PyMC3 Version: v3.11.4
* Aesara/Theano Version: v1.1.2
* Python Version: 3.9.7
* Operating system: Windows 10
* How did you install PyMC3: (conda/pip): conda create -n pm3env -c conda-forge "python=3.8" libpython mkl-service m2w64-toolchain numba python-graphviz scipy and then pip install pymc3

**Comment by michaelosthege** [comment]
I bet 80 % that's because of the system-wide MinGW in your PATH.

Also note this part of the last line in your traceback:
```
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file
```

I don't know what this `TDM-GCC-64` is that you have installed, but it doesn't look like these compilers are coming from your Python environment.

**Comment by Hemming01** [comment]
Thanks a lot Michael! Much appreciated.

I think I had messed up the environment. I started all over with reinstalling everything and now it runs.

Sorry for asking. Is there currently any solution for the issue with using NumPy (WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.) for Windows? I simply can't find any solution anywhere.

**Comment by michaelosthege** [comment]
👍

The BLAS thing is basically a matter of getting a nice NumPy installation. If the conda install command from the guide doesn't work you can try the `environment.yml` also from the Guide.

I got to admit this is something I also don't get right every time.

**Comment by Hemming01** [comment]
> 👍
> 
> The BLAS thing is basically a matter of getting a nice NumPy installation. If the conda install command from the guide doesn't work you can try the `environment.yml` also from the Guide.
> 
> I got to admit this is something I also don't get right every time.

Hehe. Thanks for replying! I'll try to google some more.
