### ISSUE TITLE
Homebrew Installed PYMC2.3

### ISSUE THREAD

**Issue by pnkelly** [pymc-devs/pymc3#520]
I have just installed pymc using home-brew: pip install pymc. 
I am going through the tutorial found here: https://github.com/pymc-devs/pymc/tree/2.3,
and this line has failed: pymc.Matplot.plot(S).

The error is:

```
ln [5]: pymc.Matplot.plot(S)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-b825c264da3f> in <module>()
----> 1 pymc.Matplot.plot(S)

AttributeError: 'module' object has no attribute 'Matplot'
```

Is the homebrew'ed option out of date? Why was I able to import pymc without Matplot?

Thanks!

edit -- this is an home-brew matplotlib issue, not pymc.
edit -- matplotlib now imports without error, the Attribute Error has not gone away. 

Here is the output of pymc.test(), what happened?

```
In [4]: pymc.test()
Running unit tests for pymc.tests
NumPy version 1.8.1
NumPy is installed in /usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy
Python version 2.7.6 (default, Mar 26 2014, 10:17:18) [GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)]
nose version 1.3.0
Plotting disabled
..S.S..S........EEEE..S.............S............................................................................................................SS......E............./usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_utils.py:15: RuntimeWarning: invalid value encountered in sqrt
  C = Lambda('C', lambda b=B: sqrt(b))
.........
======================================================================
ERROR: test_simple (pymc.tests.test_convergence.test_gelman_rubin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 94, in test_simple
    gr = pymc.gelman_rubin(S2)
AttributeError: 'module' object has no attribute 'gelman_rubin'

======================================================================
ERROR: test_independent (pymc.tests.test_convergence.test_geweke)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 56, in test_independent
    x = [pymc.geweke(np.random.normal(size=1000), intervals=5)[0][1] for _ in range(10000)]
AttributeError: 'module' object has no attribute 'geweke'

======================================================================
ERROR: test_simple (pymc.tests.test_convergence.test_geweke)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 69, in test_simple
    scores = pymc.geweke(S, intervals=intervals)
AttributeError: 'module' object has no attribute 'geweke'

======================================================================
ERROR: test_simple (pymc.tests.test_convergence.test_iat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 104, in test_simple
    iat = pymc.iat(x)
AttributeError: 'module' object has no attribute 'iat'

======================================================================
ERROR: Failure: ImportError (No module named six)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_missing.py", line 1, in <module>
    from pymc import rnormal, Normal, MCMC, Uniform, Matplot, Metropolis
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/Matplot.py", line 14, in <module>
    from pylab import hist, plot as pyplot, xlabel, ylabel, xlim, ylim, savefig, acorr, mlab
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/pylab.py", line 226, in <module>
    import matplotlib.finance
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/finance.py", line 21, in <module>
    from matplotlib.dates import date2num
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/dates.py", line 119, in <module>
    from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dateutil/rrule.py", line 18, in <module>
    from six import advance_iterator, integer_types
ImportError: No module named six

----------------------------------------------------------------------
Ran 175 tests in 6.105s

FAILED (SKIP=7, errors=5)
Out[4]: <nose.result.TextTestResult run=175 errors=5 failures=0>
```

**Comment by fonnesbeck** [comment]
Is there a problem here we can help you with?

**Comment by pnkelly** [comment]
Yes, I have updated my original question.

**Comment by fonnesbeck** [comment]
PyMC has not been installed properly. Can you recount what you did to install? -- You said you used homebrew to install pymc, but it looks like you used pip. Did it install cleanly? Maybe try again and show the output.

**Comment by pnkelly** [comment]
Yes, I am using pip, which I got from homebrew. Sorry for the misunderstanding. 
The output from my installation is rather large, but this is some what shows up at the bottom:

```
2 warnings generated.
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -fPIC -O3 -funroll-loops
compile options: '-DNO_ATLAS_INFO=3 -Ibuild/src.macosx-10.9-x86_64-2.7 -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
gfortran:f77: pymc/gp/cov_funs/distances.f
pymc/gp/cov_funs/distances.f:138.24:

                theta = DATAN2(dlat/a,dlon/a)/pi
                        1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
/usr/local/bin/gfortran -Wall -Wall -undefined dynamic_lookup -bundle build/temp.macosx-10.9-x86_64-2.7/build/src.macosx-10.9-x86_64-2.7/pymc/gp/cov_funs/distancesmodule.o build/temp.macosx-10.9-x86_64-2.7/build/src.macosx-10.9-x86_64-2.7/fortranobject.o build/temp.macosx-10.9-x86_64-2.7/pymc/gp/cov_funs/distances.o -L/usr/local/Cellar/gfortran/4.8.2/gfortran/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -o build/lib.macosx-10.9-x86_64-2.7/pymc/gp/cov_funs/distances.so -Wl,-framework -Wl,Accelerate

warning: no files found matching 'docs/UserGuide.pdf'
warning: no files found matching '*.txt' under directory 'pymc'
customize UnixCCompiler
```

Successfully installed pymc
Cleaning up...

**Comment by fonnesbeck** [comment]
I have not really tried installing PyMC into a homebrew Python, but it appears that not all the prerequisites have been installed. You might try:

```
pip install six
```

I'm not sure why PyMC is not finding some of its objects, however. What pip command are you using? If you want to post the entire object, pop it into a Gist and post a link to it.

**Comment by fonnesbeck** [comment]
By the way, I do distribute binaries of the Python scientific stack (including PyMC 2.3) in the [Scipy Superpack](http://fonnesbeck.github.io/ScipySuperpack/), if you want to give that a try. By default, it installs with the Python at /usr/bin/python (usually the Python that ships with OS X), but you can change the path in the install script to install elsewhere.

**Comment by pnkelly** [comment]
I already have six installed:
Priscillas-MacBook-Pro:montepython priscillakelly$ pip install six
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages
Cleaning up...

I will try the scipy superpack, but I'll have to change the installation path.
Thank you.
