### ISSUE TITLE
"pip install" from github doesn't include pymc.examples

### ISSUE THREAD

**Issue by andrewclegg** [pymc-devs/pymc3#531]
I recently installed from master like so:

```
pip3.4 install git+https://github.com/pymc-devs/pymc.git@a8c872c25dc8ed8235b248c3ff1deba160eb9d8d
```

(this is the tip of master at the time of writing)

This doesn't include pymc.examples, as this package isn't listed in setup.py:

```
      packages=['pymc', 'pymc.distributions',
                'pymc.step_methods', 'pymc.tuning', 
                'pymc.tests', 'pymc.glm'],
```

But quite a few tests depend on pymc.examples, so when I do

```
import pymc
pymc.test()
```

to check my installation, I get a bunch of errors.

Is this intentional? Would it be particularly costly or awkward to include pymc.examples in setup.py, or is there some other reason it's not included?

Testing with python 3.4 -- maybe a bit adventurous -- but I don't think this is a problem in this particular case.

Thanks :-)

**Comment by fonnesbeck** [comment]
Give the `examples_install` branch a try. I added `examples` to the packages list.

**Comment by andrewclegg** [comment]
Thanks @fonnesbeck -- I will test tomorrow and get back to you.

**Comment by andrewclegg** [comment]
Unfortunately, that gives me this:

```
error: package directory 'pymc/backends' does not exist
```

I tried with both

```
sudo pip install git+https://github.com/pymc-devs/pymc.git@examples_install
```

and

```
sudo pip install git+https://github.com/pymc-devs/pymc.git@b1058549e69f09c5915e3f683e441bd1070c7645
```

**Comment by kyleam** [comment]
Looks like `pymc.backends` was added on accident (it relates to an unmerged PR). I've update the branch.

**Comment by andrewclegg** [comment]
Still getting a few errors, some of them don't seem to be related to pymc.examples, so I'll raise a separate ticket for them if I can't get to the bottom of them.

These look relevant though:

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples2('pymc.examples.stochastic_volatility',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/stochastic_volatility.py", line 41, in <module>
    returns = np.genfromtxt(get_data_file('pymc.examples', "data/SP500.csv"))[-n:]
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/SP500.csv'
```

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.GHME_2013',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/GHME_2013.py", line 17, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/pancreatitis/input_data.csv'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/pancreatitis/input_data.csv'
```

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM5_4',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM5_4.py", line 11, in <module>
    wells = get_data_file('pymc.examples', 'data/wells.dat')
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/wells.dat'
```

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM12_6uranium',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM12_6uranium.py", line 5, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/srrs2.dat'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/srrs2.dat'
```

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM12_6',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM12_6.py", line 5, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/srrs2.dat'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/srrs2.dat'
```

**Comment by fonnesbeck** [comment]
Sorry, forgot about subdirectories. This should do it.

**Comment by andrewclegg** [comment]
Thanks! Just re-running my build/test script now, will check it over the weekend at some point (it takes a while...) and close this off.

**Comment by andrewclegg** [comment]
I think something is still missing, I'm afraid!

I get this appearing in the output from `pip install`:

```
package init file 'pymc/examples/data/__init__.py' not found (or not a regular file)
```

Then the following tests fail:

```
======================================================================
ERROR: pymc.tests.test_examples.test_examples2('pymc.examples.stochastic_volatility',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/stochastic_volatility.py", line 41, in <module>
    returns = np.genfromtxt(get_data_file('pymc.examples', "data/SP500.csv"))[-n:]
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/SP500.csv'

======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM12_6',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM12_6.py", line 5, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/srrs2.dat'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/srrs2.dat'

======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM12_6uranium',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM12_6uranium.py", line 5, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/srrs2.dat'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/srrs2.dat'

======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.ARM5_4',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/ARM5_4.py", line 11, in <module>
    wells = get_data_file('pymc.examples', 'data/wells.dat')
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/wells.dat'

======================================================================
ERROR: pymc.tests.test_examples.test_examples0('pymc.examples.GHME_2013',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.4/dist-packages/pymc/tests/test_examples.py", line 13, in check_example
    example = __import__(example_name, fromlist='dummy')
  File "/usr/local/lib/python3.4/dist-packages/pymc/examples/GHME_2013.py", line 17, in <module>
    data = pd.read_csv(get_data_file('pymc.examples', 'data/pancreatitis.csv'))
  File "/usr/local/lib/python3.4/dist-packages/pymc/data.py", line 20, in get_data_file
    return io.BytesIO(pkgutil.get_data(pkg, path))
  File "/usr/lib/python3.4/pkgutil.py", line 625, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1600, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/pymc/examples/data/pancreatitis.csv'

----------------------------------------------------------------------
```

**Comment by fonnesbeck** [comment]
Sorry, the init file should be there now. Try again.

**Comment by fonnesbeck** [comment]
Thanks! I did not know about `package_data`.

**Comment by andrewclegg** [comment]
No problem! Me neither :-)

TBH I haven't re-run the whole test suite yet, just doing that now, but the files are definitely in the right place now.

**Comment by andrewclegg** [comment]
Tests passed ok.
