### ISSUE TITLE
Seg fault on observed Binomial

### ISSUE THREAD

**Issue by rsepassi** [pymc-devs/pymc3#545]
May be a duplicate of #180 .

The code below errors out with message `Segmentation Fault: 11`. Have tried it on several Mac OS X computers, all Mavericks, all running Python 2.7.6, pymc 2.3.2. 

Simple model for an A/B test:

``` python
# coding: utf-8
import pymc as pm
import pymc.graph

pA = pm.Uniform('pA', 0, 1)
pB = pm.Uniform('pB', 0, 1)

@pm.deterministic
def p_delta(pA=pA, pB=pB):
    return pA - pB

obsA = pm.rbernoulli(0.55, 1500)
obsB = pm.rbernoulli(0.45, 750)

dataA = pm.Binomial('ctrA', len(obsA), pA, value=obsA, observed=True)
dataB = pm.Binomial('ctrB', len(obsB), pB, value=obsB, observed=True)

model = pm.Model([pA, pB, p_delta, dataA, dataB])

graph = pm.graph.graph(model)
graph.write_png('ab_test_observed.png')
```

Sometimes the seg fault comes with more information:

```
Traceback (most recent call last):
  File "ab_test_error.py", line 15, in <module>
    dataA = pm.Binomial('ctrA', len(obsA), pA, value=obsA, observed=True)
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/distributions.py", line 271, in __init__
    Stochastic.__init__(self, logp=logp, random=random, logp_partial_gradients = logp_partial_gradients, dtype=dtype, **arg_dict_out)
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 748, in __init__
    verbose=verbose)
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/Node.py", line 216, in __init__
    Node.__init__(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/Node.py", line 127, in __init__
    self.parents = parents
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/Node.py", line 150, in _set_parents
    self.gen_lazy_function()
  File "/Users/Ryan/.virtualenvs/sci/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 806, in gen_lazy_function
    lazy_logp_partial_gradient.force_compute()
  File "LazyFunction.pyx", line 260, in pymc.LazyFunction.LazyFunction.force_compute (pymc/LazyFunction.c:2432)
  File "LazyFunction.pyx", line 209, in pymc.LazyFunction.LazyFunction.cache (pymc/LazyFunction.c:1880)
IndexError: list assignment index out of range
Segmentation fault: 11
```

Occasionally I get this error instead:

```
python(12569,0x7fff74ca7310) malloc: *** error for object 0x7f980c972268: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by timothyrenner** [comment]
I've seen the same thing on one of my models with binomials, never get the error beyond segmentation fault though.

I'm running it on a virtualbox-backed vagrant image of the data science toolbox. Python 2.7.5+, pymc version 2.3.2.

**Comment by fonnesbeck** [comment]
A couple of issues here: You seem to simulate bernoulli data, but feed it into a Binomial likelihood with N>1. Seems like you should either be using a Bernoulli likelihood, or summing the data somehow to create binomial data.

Also, you instantiate a `Model` class, which is not intended to be directly instantiated. If you plan to use MCMC then instantiate an `MCMC` class, or one of the approximation classes if you intend to approximate.

The following code runs without error:

```
import pymc as pm
import pymc.graph

pA = pm.Uniform('pA', 0, 1)
pB = pm.Uniform('pB', 0, 1)

@pm.deterministic
def p_delta(pA=pA, pB=pB):
    return pA - pB

obsA = pm.rbernoulli(0.55, 1500)
obsB = pm.rbernoulli(0.45, 750)

dataA = pm.Binomial('ctrA', len(obsA), pA, value=sum(obsA), observed=True)
dataB = pm.Binomial('ctrB', len(obsB), pB, value=sum(obsB), observed=True)

model = pm.MCMC([pA, pB, p_delta, dataA, dataB])

graph = pm.graph.graph(model)
graph.write_png('ab_test_observed.png')
```

**Comment by timothyrenner** [comment]
I made the same mistake in my model. Switching the binomial to a Bernoulli solved it. Thanks!
