### ISSUE TITLE
Disable figure pop-ups while running tests?

### ISSUE THREAD

**Issue by cdeil** [pymc-devs/pymc3#59]
When running pymc.test() there are a lot of annoying figure pop-ups (seem to be empty). Can these be disabled?

Also I got an error and 4 failures, although I think there are other open tickets for these already:

``` text
In [2]: pymc.__version__
Out[2]: '2.2grad'

In [3]: pymc.test()
Running unit tests for pymc.tests
NumPy version 1.6.1
NumPy is installed in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy
Python version 2.7.2 (default, Jul 23 2011, 13:25:29) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]
nose version 1.0.0
..................F.........................S....../opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/database/hdf5.py:448: UserWarning: 
Error tallying K, will not try to tally it again this chain.
Did you make all the samevariables and step methods tallyable
as were tallyable last time you used the database file?

Error:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/database/hdf5.py", line 438, in tally
    self._traces[name].tally(chain)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/database/hdf5.py", line 57, in tally
    self._vlarrays[chain].append(self._getfunc())
IndexError: list index out of range

  %s"""%(name, ''.join(traceback.format_exception(cls, inst, tb))))
FFF.............................................................................................E...SS.....................
======================================================================
ERROR: test_gradients (pymc.tests.test_gradients.test_gradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_gradients.py", line 340, in test_gradients
    negative_binomial = NegativeBinomial('negative_binomial', mu = c, alpha = d )
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/distributions.py", line 269, in __init__
    Stochastic.__init__(self, logp=logp, random=random, logp_partial_gradients = logp_partial_gradients, dtype=dtype, **arg_dict_out)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 691, in __init__
    verbose=verbose)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/Node.py", line 193, in __init__
    Node.__init__(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/Node.py", line 111, in __init__
    self.parents = parents
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/Node.py", line 132, in _set_parents
    self.gen_lazy_function()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 731, in gen_lazy_function
    self._logp.force_compute()
  File "LazyFunction.pyx", line 256, in pymc.LazyFunction.LazyFunction.force_compute
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/distributions.py", line 2918, in wrapper
    return f(value, **kwds)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/distributions.py", line 2076, in negative_binomial_like
    if alpha > 1e10:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
FAIL: test_simple (pymc.tests.test_convergence.test_raftery_lewis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 72, in test_simple
    assert(0.8 < (float(nprec)/kmind) / nmin < 1.2)
AssertionError

======================================================================
FAIL: test_simple_sample (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_database.py", line 287, in test_simple_sample
    assert_array_equal(self.S.trace('K')[:].shape, (10,))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([0])
 y: array([10])

======================================================================
FAIL: test_xload (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_database.py", line 300, in test_xload
    assert_array_equal(db.K().shape, (10,))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([0])
 y: array([10])

======================================================================
FAIL: test_yconnect_and_sample (pymc.tests.test_database.testHDF5Objects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymc/tests/test_database.py", line 311, in test_yconnect_and_sample
    assert_array_equal(db.K(chain=1).shape, (10,))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([0])
 y: array([10])

----------------------------------------------------------------------
Ran 174 tests in 33.907s

FAILED (SKIP=3, errors=1, failures=4)
Out[3]: <nose.result.TextTestResult run=174 errors=1 failures=4>
```

**Comment by fonnesbeck** [comment]
Those are figures generated by the unit tests. They are not empty; you will find them written to the testresults folder in your current directory.

**Comment by cdeil** [comment]
What I meant is that the pop-ups are an unnecessary distraction, because it is impossible to see the interactive plots.

I just realized that `matplotlib.test()` also produces interactive figures (and crashes when run in ipython :-), so I guess there is a reason to not simply write the figures to file without interactive plots in the tests.

**Comment by fonnesbeck** [comment]
OK, cool. The unit test failures correspond to existing issues, namely #57 and #58.
