### ISSUE TITLE
test suite fails with 10 errors

### ISSUE THREAD

**Issue by ocramz** [pymc-devs/pymc3#621]
Hi, I get 10 errors and the test suite fails:
(OSX 10.9, Python 2.7.5 (default, Sep 12 2013, 21:33:34), [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin)
logs (from the final part of the pymc installation to the whole test suite ) follow;
Kind regards

```
Adding pymc 2.3.3 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg
Processing dependencies for pymc
Finished processing dependencies for pymc
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/distutils/misc_util.py:252: RuntimeWarning: Parent module 'numpy.distutils' not found while handling absolute import
  from numpy.distutils import log


>>> pymc.test()
Running unit tests for pymc.tests
NumPy version 1.9.0
NumPy is installed in /Library/Python/2.7/site-packages/numpy-1.9.0-py2.7-macosx-10.9-intel.egg/numpy
Python version 2.7.5 (default, Sep 12 2013, 21:33:34) [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
nose version 1.3.3
..../Library/Python/2.7/site-packages/numpy-1.9.0-py2.7-macosx-10.9-intel.egg/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
......../Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py:408: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.__name__ = input['__name__']
/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py:408: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.__name__ = input['__name__']
..........S..EEEE.E....ES..EEEE......................................................................................................SS...................[-----------------100%-----------------] 1000 of 1000 complete in 0.4 sec
.[-----------------100%-----------------] 1000 of 1000 complete in 0.1 sec
............
======================================================================
ERROR: test_simple_sample (pymc.tests.test_database.TestPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 74, in test_simple_sample
    self.S.sample(50, 25, 5, progress_bar=0)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 277, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 251, in sample
    self._loop()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 313, in _loop
    step_method.step()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 500, in step
    logp = self.logp_plus_loglike
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 313, in logp_plus_loglike
    sum = logp_of_set(self.markov_blanket)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py", line 30, in logp_of_set
    logp += obj.logp
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/PyMCObjects.py", line 929, in get_logp
    raise ZeroProbability(self.errmsg)
ZeroProbability: Stochastic early_mean's value is outside its support,
 or it forbids its parents' current values.

======================================================================
ERROR: test_xload (pymc.tests.test_database.TestPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 178, in test_xload
    db = self.load()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 175, in load
    os.path.join(testdir, 'Disaster.pickle'))
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/database/pickle.py", line 82, in load
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'testresults/Disaster.pickle'

======================================================================
ERROR: test_yconnect_and_sample (pymc.tests.test_database.TestPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 190, in test_yconnect_and_sample
    db = self.load()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 175, in load
    os.path.join(testdir, 'Disaster.pickle'))
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/database/pickle.py", line 82, in load
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'testresults/Disaster.pickle'

======================================================================
ERROR: test_yrestore_state (pymc.tests.test_database.TestPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 223, in test_yrestore_state
    db = self.load()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 175, in load
    os.path.join(testdir, 'Disaster.pickle'))
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/database/pickle.py", line 82, in load
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'testresults/Disaster.pickle'

======================================================================
ERROR: test_simple_sample (pymc.tests.test_database.TestRam)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 74, in test_simple_sample
    self.S.sample(50, 25, 5, progress_bar=0)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 277, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 251, in sample
    self._loop()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 313, in _loop
    step_method.step()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 500, in step
    logp = self.logp_plus_loglike
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 313, in logp_plus_loglike
    sum = logp_of_set(self.markov_blanket)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py", line 30, in logp_of_set
    logp += obj.logp
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/PyMCObjects.py", line 929, in get_logp
    raise ZeroProbability(self.errmsg)
ZeroProbability: Stochastic early_mean's value is outside its support,
 or it forbids its parents' current values.

======================================================================
ERROR: test_yconnect_and_sample (pymc.tests.test_database.TestSqlite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 194, in test_yconnect_and_sample
    S.sample(5, progress_bar=0)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 277, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 251, in sample
    self._loop()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 313, in _loop
    step_method.step()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 500, in step
    logp = self.logp_plus_loglike
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 313, in logp_plus_loglike
    sum = logp_of_set(self.markov_blanket)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py", line 30, in logp_of_set
    logp += obj.logp
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/PyMCObjects.py", line 929, in get_logp
    raise ZeroProbability(self.errmsg)
ZeroProbability: Stochastic early_mean's value is outside its support,
 or it forbids its parents' current values.

======================================================================
ERROR: test_simple_sample (pymc.tests.test_database.TestTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 74, in test_simple_sample
    self.S.sample(50, 25, 5, progress_bar=0)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 277, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 251, in sample
    self._loop()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 313, in _loop
    step_method.step()
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 500, in step
    logp = self.logp_plus_loglike
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/StepMethods.py", line 313, in logp_plus_loglike
    sum = logp_of_set(self.markov_blanket)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Node.py", line 30, in logp_of_set
    logp += obj.logp
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/PyMCObjects.py", line 929, in get_logp
    raise ZeroProbability(self.errmsg)
ZeroProbability: Stochastic early_mean's value is outside its support,
 or it forbids its parents' current values.

======================================================================
ERROR: test_xload (pymc.tests.test_database.TestTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 179, in test_xload
    assert_array_equal(db.trace('early_mean', chain=0)[:].shape, (5,))
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/database/base.py", line 373, in trace
    trace = copy.copy(self._traces[name])
KeyError: 'early_mean'

======================================================================
ERROR: test_yconnect_and_sample (pymc.tests.test_database.TestTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 191, in test_yconnect_and_sample
    S = pymc.MCMC(disaster_model, db=db)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 82, in __init__
    **kwds)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 220, in __init__
    v.trace = self.db._traces[v.__name__]
KeyError: 'late_mean'

======================================================================
ERROR: test_yrestore_state (pymc.tests.test_database.TestTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/tests/test_database.py", line 224, in test_yrestore_state
    S = pymc.MCMC(disaster_model, db=db)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/MCMC.py", line 82, in __init__
    **kwds)
  File "/Library/Python/2.7/site-packages/pymc-2.3.3-py2.7-macosx-10.9-intel.egg/pymc/Model.py", line 220, in __init__
    v.trace = self.db._traces[v.__name__]
KeyError: 'late_mean'

----------------------------------------------------------------------
Ran 178 tests in 30.325s

FAILED (SKIP=4, errors=10)
<nose.result.TextTestResult run=178 errors=10 failures=0>
```

**Comment by fonnesbeck** [comment]
It would be great to see the install log, as well as the versions of your dependencies. Also, try installing from the 2.3 branch, or the 2.3.4 release, if possible.

**Comment by ocramz** [comment]
Hi there!
please find the complete log file here:

https://gist.github.com/ocramz/479ac16247c4c9cbfc6c

In the meantime I'll try with version 2.3.4
Thank you and KR;

**Comment by ocramz** [comment]
> > > pymc.**version**
> > > '2.3.3'
> > > numpy.**version**
> > > '1.9.0'
> > > scipy.**version**
> > > '0.11.0'
> > > nose.**version**
> > > '1.3.3'

By installing PyMC 2.3.3 in fresh virtualenv with all the latest dependencies, the test suite works:

OK (SKIP=4)
<nose.result.TextTestResult run=178 errors=0 failures=0>
