### ISSUE TITLE
ImportError after install

### ISSUE THREAD

**Issue by mccarthyryanc** [pymc-devs/pymc3#626]
I get an ImportError when trying to use PyMC 3:

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc as pm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc/__init__.py", line 9, in <module>
    from .interactive_sampling import *
  File "/usr/local/lib/python2.7/dist-packages/pymc/interactive_sampling.py", line 1, in <module>
    from IPython.html import widgets
ImportError: cannot import name widgets
>>> 
```

**System Info:**
- Ubuntu 14.04: 3.13.0-37-generic #64-Ubuntu

**Install Method:**

```
$ sudo pip install git+https://github.com/pymc-devs/pymc
Downloading/unpacking git+https://github.com/pymc-devs/pymc
  Cloning https://github.com/pymc-devs/pymc to /tmp/pip-yg7BIu-build
  Running setup.py (path:/tmp/pip-yg7BIu-build/setup.py) egg_info for package from git+https://github.com/pymc-devs/pymc

Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/local/lib/python2.7/dist-packages (from pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.12.0 in /usr/local/lib/python2.7/dist-packages (from pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): matplotlib>=1.2.1 in /usr/local/lib/python2.7/dist-packages (from pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): Theano<=0.7dev in /usr/local/lib/python2.7/dist-packages (from pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.2.1->pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.2.1->pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.2.1->pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.2.1->pymc==3.0)
Requirement already satisfied (use --upgrade to upgrade): mock in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.2.1->pymc==3.0)
Installing collected packages: pymc
  Running setup.py install for pymc

Successfully installed pymc
Cleaning up...
```

**Comment by mccarthyryanc** [comment]
Just tested with IPython 2.1.0 and everything seems to work. I previously had IPython 1.2.1 installed. Should IPython be added to the list of dependecies?

**Comment by twiecki** [comment]
Ah, yes. We might want to localize the import into `nbsample`. What do you think @akloster?

**Comment by akloster** [comment]
Yes, definitely...

**Comment by twiecki** [comment]
Want to do a PR?

**Comment by akloster** [comment]
Yes, I am working on it.
