### ISSUE TITLE
pymc.test() failures (just installed + new user...)

### ISSUE THREAD

**Issue by wodell** [pymc-devs/pymc3#65]
OSX 10.6.8 + pymc built from source. 

```
Python 2.6.1 (r261:67515, Aug  2 2010, 20:10:18) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymc
>>> pymc.test()
Running unit tests for pymc.tests
NumPy version 2.0.0.dev-b5cdaee
NumPy is installed in /Library/Python/2.6/site-packages/numpy-2.0.0.dev_b5cdaee_20110710-py2.6-macosx-10.6-universal.egg/numpy
Python version 2.6.1 (r261:67515, Aug  2 2010, 20:10:18) [GCC 4.2.1 (Apple Inc. build 5646)]
nose version 1.1.2
..E...............F..S.............S......S............................../Library/Python/2.6/site-packages/scipy-0.10.0.dev_20110710-py2.6-macosx-10.6-universal.egg/scipy/stats/distributions.py:1256: DeprecationWarning: putmask has been deprecated. Use copyto with 'where' as the mask instead
  putmask(output,(1-cond0)*array(cond1,bool),self.badvalue)
......../Library/Python/2.6/site-packages/scipy-0.10.0.dev_20110710-py2.6-macosx-10.6-universal.egg/scipy/stats/distributions.py:3246: DeprecationWarning: putmask has been deprecated. Use copyto with 'where' as the mask instead
  putmask(logpdf,(c==1) & (x==1),0.0) # logpdf(c==1 & x==1) = 0; % 0^0 situation
.......................................................E.E.SS.....................
======================================================================
ERROR: test_autocorrelation (pymc.tests.test_MCMCSampler.test_MCMC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_MCMCSampler.py", line 49, in test_autocorrelation
    autocorrelation(self.M.early_mean, path=DIR,  verbose=0)
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/Matplot.py", line 326, in wrapper
    f(data, name, *args, **kwargs)
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/Matplot.py", line 691, in autocorrelation
    setp(tlabels, 'fontsize', fontmap[rows/2])
KeyError: 0.5

======================================================================
ERROR: test_gradients (pymc.tests.test_gradients.test_gradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 281, in test_gradients
    check_gradients(norm2)
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 107, in check_gradients
    numeric_gradient = get_numeric_gradient(stochastics, s)
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 129, in get_numeric_gradient
    delta[unravel_index(i,i_shape)] += e
ValueError: dims must have at least one value

======================================================================
ERROR: test_model (pymc.tests.test_gradients.test_gradients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 355, in test_model
    check_gradients(model[0])
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 107, in check_gradients
    numeric_gradient = get_numeric_gradient(stochastics, s)
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_gradients.py", line 129, in get_numeric_gradient
    delta[unravel_index(i,i_shape)] += e
ValueError: dims must have at least one value

======================================================================
FAIL: test_simple (pymc.tests.test_convergence.test_raftery_lewis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/pymc-2.2alpha-py2.6-macosx-10.6-universal.egg/pymc/tests/test_convergence.py", line 72, in test_simple
    assert(0.8 < (float(nprec)/kmind) / nmin < 1.2)
AssertionError

----------------------------------------------------------------------
Ran 161 tests in 19.573s

FAILED (SKIP=5, errors=3, failures=1)
<nose.result.TextTestResult run=161 errors=3 failures=1>
>>>
```

**Comment by fonnesbeck** [comment]
Hi Mike,

Where did you get your source from? Some of those errors look old. The last one is stochastic, and should not occur all the time, and the ones related to gradients are only going to be an issue if you use gradient methods (they are known errors).

**Comment by wodell** [comment]
clone https://github.com/pymc-devs/pymc.git today.  It wasn't clear to me
whether I should prefer the Snow Leopard binary or the source.  I got the
feeling from the project page that pulling from source was preferred.

Cheers!
Mike

**Comment by fonnesbeck** [comment]
What version of matplotlib are you using? Some of those errors seem to be related with plotting. If it is older, you might want to update.

**Comment by wodell** [comment]
/Library/Python/2.6/site-packages/matplotlib-1.1.0-py2.6-macosx-10.6-universal.egg/matplotlib/**init**.py

Thanks!
Mike

**Comment by fonnesbeck** [comment]
I believe you are using older PyMC code, as the line numbers in your errors do not correspond to their location in the existing codebase. The first error, for example, has been fixed in the master branch on GitHub (https://github.com/pymc-devs/pymc/blob/master/pymc/Matplot.py). Please check your installation again.

**Comment by wodell** [comment]
Will do!

Thanks,
Mike
