### ISSUE TITLE
pymc.test() error: test_gradients in test_simple (just installed + new user...)

### ISSUE THREAD

**Issue by bertelsen** [pymc-devs/pymc3#67]
Mac OS X 10.6, fink tools, pymc-devs-pymc-raked_sandbox-161-gf0ad9f7 (latest git clone) 

Output below. Best regards, Tomas

---

Python 2.7.2 (default, Aug 10 2011, 12:17:29) 
Type "copyright", "credits" or "license" for more information.

IPython 0.11 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import pymc

In [2]: pymc.test()
Running unit tests for pymc.tests
NumPy version 1.6.1
NumPy is installed in /sw/lib/python2.7/site-packages/numpy
Python version 2.7.2 (default, Aug 10 2011, 12:17:29) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
nose version 1.1.2
# ..................F..S.............S......S.............................................................................................E..........................
## ERROR: test_gradients (pymc.tests.test_gradients.test_gradients)

Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/pymc/tests/test_gradients.py", line 340, in test_gradients
    negative_binomial = NegativeBinomial('negative_binomial', mu = c, alpha = d )
  File "/sw/lib/python2.7/site-packages/pymc/distributions.py", line 269, in **init**
    Stochastic.**init**(self, logp=logp, random=random, logp_partial_gradients = logp_partial_gradients, dtype=dtype, *_arg_dict_out)
  File "/sw/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 691, in **init**
    verbose=verbose)
  File "/sw/lib/python2.7/site-packages/pymc/Node.py", line 193, in **init**
    Node.**init**(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/sw/lib/python2.7/site-packages/pymc/Node.py", line 111, in **init**
    self.parents = parents
  File "/sw/lib/python2.7/site-packages/pymc/Node.py", line 132, in _set_parents
    self.gen_lazy_function()
  File "/sw/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 731, in gen_lazy_function
    self._logp.force_compute()
  File "LazyFunction.pyx", line 256, in pymc.LazyFunction.LazyFunction.force_compute
  File "/sw/lib/python2.7/site-packages/pymc/distributions.py", line 2918, in wrapper
    return f(value, *_kwds)
  File "/sw/lib/python2.7/site-packages/pymc/distributions.py", line 2076, in negative_binomial_like
    if alpha > 1e10:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
# 
## FAIL: test_simple (pymc.tests.test_convergence.test_raftery_lewis)

Traceback (most recent call last):
  File "/sw/lib/python2.7/site-packages/pymc/tests/test_convergence.py", line 72, in test_simple
    assert(0.8 < (float(nprec)/kmind) / nmin < 1.2)
AssertionError

---

Ran 161 tests in 19.108s

FAILED (SKIP=3, errors=1, failures=1)
Out[2]: <nose.result.TextTestResult run=161 errors=1 failures=1>

**Comment by fonnesbeck** [comment]
The ValueError has been fixed in commit 0c528330a402084d335c9204613257cc2983604c. The AssertionError is stochastic and will not occur all the time. We probably have to alter our threshold in the unit test.
